### ISSUE TITLE
Missing dependencies in `docs/requirements.txt`.

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#408]
#### Problem description
Doc generation seems to be failing because of missing dependencies in `docs/requirements.txt`. Chiefly, squalchemy and pylru.

**Comment by ChristianLieven** [comment]
@Midnighter Is this one fixed now that you've done some dependency magic?

**Comment by Midnighter** [comment]
No, I haven't looked at the documentation generation yet.

**Comment by Midnighter** [comment]
Documentation building is not fully resolved but I'm certain that adding memote package dependencies to `docs/requirements.txt` is not the way forward. I will solve it differently.
